from django.core.management.base import BaseCommand
from patients.models import Patient
from datetime import date


class Command(BaseCommand):
    help = "Add 8 patients"

    def handle(self, *args, **options):

        patients_data = [
            {
                "first_name": "Amadou",
                "last_name": "Diallo",
                "date_of_birth": date(1988, 5, 12),
                "gender": "M",
                "phone": "0612345678",
                "email": "amadou.diallo@gmail.com",
                "address_1": "12 rue de Paris",
                "address_2": "",
                "code_zone": "75010",
                "city": "Paris",
                "country": "France",
                "blood_group": "O+",
                "allergies": "Arachides",
                "chronic_diseases": "Hypertension",
                "current_treatments": "Amlodipine",
                "emergency_contact_name": "Aïssatou Diallo",
                "emergency_contact_phone": "0698765432",
                "social_security_number": "1880575123456",
                "insurance_name": "CPAM",
                "insurance_number": "CPAM123456",
            },
            {
                "first_name": "Fatou",
                "last_name": "Ba",
                "date_of_birth": date(1992, 8, 21),
                "gender": "F",
                "phone": "0622334455",
                "email": "fatou.ba@gmail.com",
                "address_1": "8 avenue Victor Hugo",
                "address_2": "Appartement 4B",
                "code_zone": "75016",
                "city": "Paris",
                "country": "France",
                "blood_group": "A+",
                "allergies": "Pollen",
                "chronic_diseases": "",
                "current_treatments": "",
                "emergency_contact_name": "Moussa Ba",
                "emergency_contact_phone": "0677889900",
                "social_security_number": "2920876123457",
                "insurance_name": "MGEN",
                "insurance_number": "MGEN789456",
            },
            {
                "first_name": "Jean",
                "last_name": "Martin",
                "date_of_birth": date(1975, 3, 2),
                "gender": "M",
                "phone": "0644556677",
                "email": "jean.martin@gmail.com",
                "address_1": "25 boulevard Voltaire",
                "address_2": "",
                "code_zone": "75011",
                "city": "Paris",
                "country": "France",
                "blood_group": "B+",
                "allergies": "",
                "chronic_diseases": "Diabète type 2",
                "current_treatments": "Metformine",
                "emergency_contact_name": "Claire Martin",
                "emergency_contact_phone": "0611223344",
                "social_security_number": "1750302123458",
                "insurance_name": "Harmonie Mutuelle",
                "insurance_number": "HM456123",
            },
            {
                "first_name": "Aïcha",
                "last_name": "Sy",
                "date_of_birth": date(1999, 11, 15),
                "gender": "F",
                "phone": "0655667788",
                "email": "aicha.sy@gmail.com",
                "address_1": "3 rue des Lilas",
                "address_2": "",
                "code_zone": "93100",
                "city": "Montreuil",
                "country": "France",
                "blood_group": "AB+",
                "allergies": "Lactose",
                "chronic_diseases": "",
                "current_treatments": "",
                "emergency_contact_name": "Mariam Sy",
                "emergency_contact_phone": "0677001122",
                "social_security_number": "2991115123459",
                "insurance_name": "CPAM",
                "insurance_number": "CPAM998877",
            },
            {
                "first_name": "Paul",
                "last_name": "Durand",
                "date_of_birth": date(1968, 6, 30),
                "gender": "M",
                "phone": "0600112233",
                "email": "paul.durand@gmail.com",
                "address_1": "10 rue Lafayette",
                "address_2": "",
                "code_zone": "75009",
                "city": "Paris",
                "country": "France",
                "blood_group": "A-",
                "allergies": "Aspirine",
                "chronic_diseases": "Asthme",
                "current_treatments": "Ventoline",
                "emergency_contact_name": "Sophie Durand",
                "emergency_contact_phone": "0699112233",
                "social_security_number": "1680630123460",
                "insurance_name": "AXA",
                "insurance_number": "AXA112233",
            },
            {
                "first_name": "Mariam",
                "last_name": "Kane",
                "date_of_birth": date(1985, 1, 9),
                "gender": "F",
                "phone": "0677884455",
                "email": "mariam.kane@gmail.com",
                "address_1": "5 rue Nationale",
                "address_2": "",
                "code_zone": "59000",
                "city": "Lille",
                "country": "France",
                "blood_group": "O-",
                "allergies": "",
                "chronic_diseases": "Hypothyroïdie",
                "current_treatments": "Levothyrox",
                "emergency_contact_name": "Cheikh Kane",
                "emergency_contact_phone": "0612340099",
                "social_security_number": "2850109123461",
                "insurance_name": "CPAM",
                "insurance_number": "CPAM445566",
            },
            {
                "first_name": "Lucas",
                "last_name": "Petit",
                "date_of_birth": date(2001, 9, 4),
                "gender": "M",
                "phone": "0688990011",
                "email": "lucas.petit@gmail.com",
                "address_1": "7 rue Pasteur",
                "address_2": "",
                "code_zone": "69007",
                "city": "Lyon",
                "country": "France",
                "blood_group": "B-",
                "allergies": "Poils d'animaux",
                "chronic_diseases": "",
                "current_treatments": "",
                "emergency_contact_name": "Nathalie Petit",
                "emergency_contact_phone": "0666554433",
                "social_security_number": "1010904123462",
                "insurance_name": "LMDE",
                "insurance_number": "LMDE778899",
            },
            {
                "first_name": "Sokhna",
                "last_name": "Ndiaye",
                "date_of_birth": date(1990, 4, 18),
                "gender": "F",
                "phone": "0610101010",
                "email": "sokhna.ndiaye@gmail.com",
                "address_1": "22 rue Gambetta",
                "address_2": "",
                "code_zone": "33000",
                "city": "Bordeaux",
                "country": "France",
                "blood_group": "AB-",
                "allergies": "Fruits de mer",
                "chronic_diseases": "",
                "current_treatments": "",
                "emergency_contact_name": "Ousmane Ndiaye",
                "emergency_contact_phone": "0677778888",
                "social_security_number": "2900418123463",
                "insurance_name": "MAIF",
                "insurance_number": "MAIF334455",
            },
        ]

        for data in patients_data:
            Patient.objects.create(**data)

        self.stdout.write(self.style.SUCCESS("8 PATIENTS CRÉES"))